language: node_js
node_js:
  - "node"
install:
  - yarn install
cache:
  directories:
  - node_modules
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
